export const WORDS = [
    "Thread",
    "Needle",
    "Fabric",
    "Stitch",
    "Embroidery",
    "Sewing",
    "Bobbin",
    // "Cross-stitch",
    "Patchwork",
    // "Appliqué",
    "Quilting",
    "Thimble",
    "Seam",
    // "Hem",
    "Tailor",
    // "Embellishment",
    "Pattern",
    "Hoop",
    "Scissors",
    // "Pin",
    "Knot",
    "Floss",
    "Button",
    "Bobbin",
    "Beading",
    "Serger",
    "Pincushion",
    "Thimble",
    "Iron",
    "Elastic",
    "Binding",
    "Tassel",
    // "Needlework",
    "Sashiko",
    "Darning",
    "Seamstress",
    "Embroider",
    "Zigzag",
    "Pinking",
    "Overlock",
    "Bias",
    "Yarn",
    "Applique",
    "Serger",
    "Cording",
    "Hemming",
    "Tailoring",
    "Monogram",
    "Crossover",
    "Gathering",
    "Ruffling",
    "Basting",
    "Purl",
    "Grosgrain",
    "Pintuck"
]